version: "3.3"

networks:
  monitoring:
    driver: bridge

services:
  app:
    image: your-bootloader:latest
    container_name: 'your-bootloader'
    volumes:
      - /home/tolya/trash:/home/document/trash
    build:
      context: .
      dockerfile: Dockerfile
    env_file: bin/database.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${YT_DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${YT_DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${YT_DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    depends_on:
#      - postgres
    ports:
      - '8080:8080'
    networks:
      - monitoring

#  postgres:
#    image: postgres:14.1
#    env_file: bin/database.env
#    environment:
#      - POSTGRES_USER=${YT_DATABASE_USER}
#      - POSTGRES_PASSWORD=${YT_DATABASE_PASSWORD}
#      - POSTGRES_HOST_AUTH_METHOD=trust
#    ports:
#      - "5432:5432"

  prometheus:
    image: prom/prometheus:v2.4.3
    container_name: 'prometheus'
#    build: '--no-cache'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.3.0
    container_name: 'grafana'
    #    build: '--no-cache'
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/etc/grafana/dashboards
    env_file:
      - ./monitoring/grafana/config.monitoring
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring