version: "3.3"

networks:
  monitoring:
    driver: bridge

services:
  app:
    image: your-bootloader:latest
    container_name: 'your-bootloader'
    volumes:
      - /home/tolya/trash:/home/document/trash
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - '8080:8080'
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.4.3
    container_name: 'prometheus'
#    build: '--no-cache'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.3.0
    container_name: 'grafana'
    #    build: '--no-cache'
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./monitoring/grafana/config.monitoring
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    expose:
      - 9100
    networks:
      - monitoring