youtube:
  download-path: '/home/document/trash'
  bot-user-name:
  token:
  max-file-size: 1000 #Mb
  jdbc:
    schema: "public"
    properties:
    max-total: 180000
    connection:
      leak-threshold:
        ms: 180000
      wait:
        timeout:
          ms: 180000
      lifetime:
        minutes: 10
    query:
      timeout:
        ms: 180000

spring:
  datasource:
    driverClassName:
    url:
    username:
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      jvm: true