youtube:
  download-path: '/home/document/trash'
  bot-user-name:
  token:
  max-file-size: 100 #Mb

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      jvm: true