youtube:
  download-path: '/Users/vishnyakov-ap/Documents/trash'
  bot-user-name: 'SpongeBobyBot'
  token: '5231087648:AAFcCT09Bg7Sb1fpUD4KprEVIiYxEfnI7Yo'
  max-file-size: 1000

spring:
  kafka:
    consumer:
      group-id: yt-group-id
      auto-offset-reset: earliest
    bootstrap-servers: localhost:29092
    listener:
      concurrency: 10