youtube:
  download-path: '/home/document/trash'
  bot-user-name: 'test-bot-user-name'
  token: 'test-bot-token'
  max-file-size: 1000 #Mb

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      jvm: true

spring:
  kafka:
    consumer:
      group-id: yt-group-id
      auto-offset-reset: earliest
    bootstrap-servers: localhost:29092
    listener:
      concurrency: 10