apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true

providers:
  - name: 'Node monitoring'
    orgId: 1
    folder: 'NODE'
    type: file
    allowUiUpdates: false
    options:
      path: /etc/grafana/provisioning/dashboards/node-exporter.json
